apiVersion: v1
kind: Service
metadata:
  name: client-results
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: client-results-ui
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client-results-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: client-results-ui
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: client-results-ui
        image: projectepic/context_query_results:1.0.6
        ports:
        - containerPort: 5000
        env:
            - name: BUCKET_NAME
              value: twitter-users-test
            - name: GEOBUCKET_NAME
              value: geo-user-timelines
            - name: PRODUCTION
              value: "True"
